version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb+srv://user15:12345678user@cluster0.jmc7smb.mongodb.net/
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
